[features]
seeds = false
skip-lint = false
[programs.devnet]
frex = "8rWa9BXJ2X34LhR3Xb9PS3Cxnuq5VS5LGXTThnckUNCY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/random/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
