[features]
seeds = false
skip-lint = false
[programs.devnet]
frex = "DerEBo7cfrBda9n3s2Cd7ZY3PkE8TLkfr1rLk6rFGNdC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/random/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
